FROM node:14-alpine

WORKDIR /app

# ENTRYPOINT - 컨테이너 이름 뒤에 나오는 명령 앞에 추가됨. ex) npm init
ENTRYPOINT [ "npm" ]
# docker run -it -v "C:\Users\KTW\Documents\GitHub\Udemy\Docker\utility-container:/app" mynpm init
# docker run -it -v "C:\Users\KTW\Documents\GitHub\Udemy\Docker\utility-container:/app" mynpm i express --save

# docker run -it -v "C:\Users\KTW\Documents\GitHub\Udemy\Docker\utility-container:/app"  node-util npm init